name: Damage Calculation Test

on:
  push:
    branches: [ main-2024 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20.11.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    
    - run: yarn install
    - run: yarn test
